### ISSUE TITLE
Problem opening the file

### ISSUE THREAD

**Issue by jtorregl** [MathWorks-Teaching-Resources/Transfer-Function-Analysis-of-Dynamic-Systems#2]
Hello,

I'm trying to open the first live script (Part0_ConceptReview.mlx) in MATLAB R2021b and it says "Can't open file".

Can anybody tell me how I can open it?

Thanks in advance.

**Comment by callieEDU** [comment]
Hello,

There have been some changes to the file naming structure. The live script is now called ConceptReview.mlx. You can open this directly on MATLAB Online. This file should be possible to open in R2021b as well. Please let me know if you are still having issues. Thanks!
